/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlotPointLearnPanel.java
 *
 * Created on Nov 18, 2011, 5:01:42 PM
 */
package GUI;
import javax.swing.JSlider;
/**
 *
 * @author Hong Yu
 */
public class PlotPointLearnPanel extends javax.swing.JPanel {
    PlotPointLearnControl story;
    /** Creates new form PlotPointLearnPanel */
    public PlotPointLearnPanel() {
        story = new PlotPointLearnControl();
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        StoryRating = new javax.swing.JSlider();
        StoryPanel = new javax.swing.JScrollPane();
        StoryTextArea = new javax.swing.JTextArea();
        StoryPanelDescription = new javax.swing.JLabel();

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        StoryRating.setMajorTickSpacing(1);
        StoryRating.setMaximum(5);
        StoryRating.setMinimum(1);
        StoryRating.setPaintLabels(true);
        StoryRating.setPaintTicks(true);
        StoryRating.setSnapToTicks(true);
        StoryRating.setToolTipText("Rate the story from1-5");
        StoryRating.setValue(story.getRating());
        StoryRating.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                StoryRatingStateChanged(evt);
            }
        });

        StoryPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        StoryPanel.setMaximumSize(new java.awt.Dimension(62767, 62767));

        StoryTextArea.setBackground(new java.awt.Color(204, 204, 204));
        StoryTextArea.setColumns(1000);
        StoryTextArea.setEditable(false);
        StoryTextArea.setFont(new java.awt.Font("Times New Roman", 0, 18));
        StoryTextArea.setLineWrap(true);
        StoryTextArea.setRows(7);
        StoryTextArea.setText(story.showStory());
        StoryTextArea.setWrapStyleWord(true);
        StoryTextArea.setBorder(null);
        StoryPanel.setViewportView(StoryTextArea);

        StoryPanelDescription.setText("Plot Point 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StoryPanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(StoryRating, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(StoryPanelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoryRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StoryRatingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_StoryRatingStateChanged
        // TODO add your handling code here:
        JSlider src = (JSlider)evt.getSource();
        if (!src.getValueIsAdjusting()) {
            story.setRating((int)src.getValue());
            System.out.println("Rating changed to: " + story.getRating());
        }
}//GEN-LAST:event_StoryRatingStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        story.advanceStory();
        StoryPanelDescription.setText("Plot Point " + story.currentStoryNumber());
        StoryTextArea.setText(story.showStory());
        
        StoryRating.setValue(story.getRating());
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane StoryPanel;
    private javax.swing.JLabel StoryPanelDescription;
    private javax.swing.JSlider StoryRating;
    private javax.swing.JTextArea StoryTextArea;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
