/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StoryLearnPanel.java
 *
 * Created on May 1, 2011, 3:25:11 PM
 */
package GUI;

import javax.swing.JSlider;

/**
 *
 * @author Peng
 */
public class StoryLearnPanel extends javax.swing.JPanel {
    /** Story controller */
    StoryControl story;
    
    /** Creates new form StoryLearnPanel */
    public StoryLearnPanel() {
        story = new StoryControl();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StoryPanel = new javax.swing.JScrollPane();
        StoryTextArea = new javax.swing.JTextArea();
        NextButton = new javax.swing.JButton();
        PrevButton = new javax.swing.JButton();
        StoryRating = new javax.swing.JSlider();
        RatingDescription = new javax.swing.JLabel();
        StoryPanelDescription = new javax.swing.JLabel();

        StoryPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        StoryPanel.setMaximumSize(new java.awt.Dimension(62767, 62767));

        StoryTextArea.setBackground(new java.awt.Color(204, 204, 204));
        StoryTextArea.setColumns(1000);
        StoryTextArea.setEditable(false);
        StoryTextArea.setFont(new java.awt.Font("Times New Roman", 0, 18));
        StoryTextArea.setLineWrap(true);
        StoryTextArea.setRows(7);
        StoryTextArea.setText(story.showStory());
        StoryTextArea.setWrapStyleWord(true);
        StoryTextArea.setBorder(null);
        StoryPanel.setViewportView(StoryTextArea);

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        PrevButton.setText("Previous");
        PrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevButtonActionPerformed(evt);
            }
        });

        StoryRating.setMajorTickSpacing(1);
        StoryRating.setMaximum(5);
        StoryRating.setMinimum(1);
        StoryRating.setPaintLabels(true);
        StoryRating.setPaintTicks(true);
        StoryRating.setSnapToTicks(true);
        StoryRating.setToolTipText("Rate the story from1-5");
        StoryRating.setValue(story.getRating());
        StoryRating.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                StoryRatingStateChanged(evt);
            }
        });

        RatingDescription.setText("Rating");

        StoryPanelDescription.setText("Story " + story.currentStoryNumber());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StoryPanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(PrevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StoryRating, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(RatingDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StoryPanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(RatingDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoryRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        story.advanceStory();
        StoryPanelDescription.setText("Story " + story.currentStoryNumber());
        StoryTextArea.setText(story.showStory());
        if(story.endOfStory()){
            StoryTextArea.append("THE END.");
        }
        StoryRating.setValue(story.getRating());
}//GEN-LAST:event_NextButtonActionPerformed

    private void PrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevButtonActionPerformed
        // TODO add your handling code here:
        story.backtrackStory();
        StoryPanelDescription.setText("Story " + story.currentStoryNumber());
        StoryTextArea.setText(story.showStory());
        StoryRating.setValue(story.getRating());
}//GEN-LAST:event_PrevButtonActionPerformed

    private void StoryRatingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_StoryRatingStateChanged
        // TODO add your handling code here:
        JSlider src = (JSlider)evt.getSource();
        if (!src.getValueIsAdjusting()) {
            story.setRating((int)src.getValue());
            System.out.println("Rating changed to: " + story.getRating());
        }
}//GEN-LAST:event_StoryRatingStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PrevButton;
    private javax.swing.JLabel RatingDescription;
    private javax.swing.JScrollPane StoryPanel;
    private javax.swing.JLabel StoryPanelDescription;
    private javax.swing.JSlider StoryRating;
    private javax.swing.JTextArea StoryTextArea;
    // End of variables declaration//GEN-END:variables
}
